### ISSUE TITLE
Advancements not being sent

### ISSUE THREAD

**Issue by matrixis** [modmuss50/HCMC100#1]
Advancements are not being sent to the servers.
Looked through Log, seems there is some SSL errors or something.

https://pastebin.com/EgYf5UaL

**Comment by modmuss50** [comment]
This is happening becuase the API that the mod is trying to access uses Lets Encrypt for the SSL and the version of java that you are using (the one that minecraft includes in its installer by default) does not support this.

You will need to update to java_101 or newer to fix this, or speak to the devs of the api/website to change to a compatible SSL cert provider.

Sadly there is nothing I can do to fix this ;(
